### ISSUE TITLE
Parsing in 1.12.2

### ISSUE THREAD

**Issue by Morketh** [matcool/anvil-parser#12]
Using a modified version of the [top_view.py](https://github.com/matcool/anvil-parser/blob/master/examples/top_view.py) script i seem to be getting all air blocks. i have tried this on both Windows and Debian ``print("processing block: {}".format(b))`` should return the block id as provided with ``chunk.get_block(x,y,z).id`` however the debug print only returns ``None`` also sticking a debug print in just after ``b = chunk.get_block(x, y, z).id`` yields all air. Using a flat terrain gen there should be at least 1 bedrock, 2 dirt, 1 grass, plus all the random yellow wool i added.
Minecraft 1.12.2 no mods (although i did try this with mods and got the same results)
Python 3.7
World: Flat terrain with no structure gen, placed yellow wool in cube configuration
```python
## """
## Generates a image of the top view of a chunk
## Needs a textures folder with a block folder inside
## """
import sys
import os
#from PIL import Image
import anvil

def GetArgs():
    if len(sys.argv) == 1:
        print('You must give a region file')
        exit()
    else:
        region = sys.argv[1]
        chx = int(sys.argv[2])
        chz = int(sys.argv[3])
    return chx, chz, region

# chx, chz, region = GetArgs()
chx, chz, region = 3,31,"saves\\PovRay\\region\\r.0.0.mca"

chunk = anvil.Chunk.from_region(region, chx, chz)
#img = Image.new('RGBA', (16*16,16*16))
grid = [[None for i in range(16)] for j in range(16)]
for y in range(256):
    for z in range(16):
        for x in range(16):
            b = chunk.get_block(x, y, z).id
            print(b) # only returns Air
            if b == 'air' or grid[z][x] is not None:
                continue
            grid[z][x] = b
print("list texture directory")
#texturesf = os.listdir('textures/block')
texturesf = {}
textures = {}
for z in range(16):
    for x in range(16):
        b = grid[z][x]
        print("processing block: {}".format(b))
        if b is None:
            continue
        if b not in textures:
            if b+'.png' not in texturesf:
                print(f'Skipping {b}')
                textures[b] = None
                continue
#            textures[b] = Image.open(f'textures/block/{b}.png')
            print("image open")
        if textures[b] is None:
            continue
        print("img paste")
#        img.paste(textures[b], box=(x*16, z*16))

#img.show()
print("end program")```

**Comment by 0xTiger** [comment]
I've found this happens too. I think it's an issue with the changes in the chunk file format since version 1.12.2
In 1.12 and earlier versions the nbt tag in Sections is called `'Blocks'` instead of `'BlockStates'`. This means the following condition always evaluates to true and so `Chunk.getblock()` method always returns air.
https://github.com/matcool/anvil-parser/blob/0c886f4caddd5e1e69ac1dde27b821a34e797751/anvil/chunk.py#L123-L124

I'm considering submitting a PR, it seems like a hardcoded pallete would be necessary.

The following is a quick workaround if you only care about block ids:
```python
class Chunk112(anvil.Chunk):
     def get_block(self, x, y, z):
         return self.data['Sections'][y//16]['Blocks'][256*(y%16) + 16*z + x]

...
chunk = Chunk112.from_region(region, chx, chz)
...
chunk.get_block(x, y, z)
```
(you would need to also apply a map to turn block ids into instances of the Block class)
(Sorry if any of this is bad github etiquette, I'm quite new to github)

**Comment by Morketh** [comment]
Ill take a look at your workaround since i only need to know the coordinates and block ids. I'll be handling all of the other things directly in PovRay for rendering which means i have to use the geometry system they have. I look forward to seeing this actually fixed upstream 👍

**Comment by matcool** [comment]
Hi (sorry for the late response)! I've tried to fix this by making a new block class `OldBlock`, which will be returned from get_block if the chunk's data version is older than 1451. It's currently not on the master branch as I'm not sure it fully works yet, since I wasn't able to get a section with the optional `Add` tag, although I did follow [the wiki](https://minecraft.gamepedia.com/index.php?title=Chunk_format&oldid=1153403#Block_format) for it.
These changes are on commit ce0b582ae97982fb636f94155d09dd1a0a32e09b

**Comment by matcool** [comment]
For now theres no hardcoded "palette" of all the blocks, so all you get is the raw numeric IDs

**Comment by 0xTiger** [comment]
> For now theres no hardcoded "palette" of all the blocks, so all you get is the raw numeric IDs

Nice, yeah I was propsing that one was made? I'm currently working on a classmethod for `Block` that takes for example your new `OldBlock` class and creates a new instance of `Block` as best it can using the `OldBlock.id` and `OldBlock.data`.  It's not perfect but a few missing properties here and there seems as close to version agnostic as one can get

**Comment by matcool** [comment]
All the changes have been pushed to version 0.8.0
