### ISSUE TITLE
How to stream blocks? (chunk.stream_blocks)

### ISSUE THREAD

**Issue by alex4200** [matcool/anvil-parser#13]
I have been trying to use the method `stream_blocks` from `chunk.py`, but I am not quite sure to make sense out of it (version 0.6.4), minecraft version 1.16.2.

As a chunk has 16 x 256 x 16 blocks, I expect that the stream delivers 65536 blocks, but its only 4096 blocks. 

I have been trying to use `stream_blocks(section=y)` which gives an error for y>4, so `section` does not mean a 16-block vertical entity. 

Error: `KeyError: 'Tag BlockStates does not exist'`

I also tried to use the `index` of the method by using `stream_blocks(index=256*y)`, but the result was that only 4096-256*y blocks were returned. 

How can I use this method to stream ideally all 65536 blocks in a 16x256x16 section?

**Comment by matcool** [comment]
`Chunk.stream_blocks` streams blocks from a given section, and sections are 16x16x16, which is why you only get 4096 blocks.
If you want to stream the entire chunk you could do something like:
```py
def stream_whole_chunk(chunk):
    for section in range(16):
        for block in chunk.stream_blocks(section=section):
            yield block
```
But on 9c7256665b208e936147d3a787949b205519c97f I added `Chunk.stream_chunk` which does the same thing

As for the KeyError I fixed it in a59532d370560766a0339e42d7c1e580c7d00010
