### ISSUE TITLE
What order does stream_blocks() follow?

### ISSUE THREAD

**Issue by jchubber** [matcool/anvil-parser#40]
_(Thank you so much for releasing this great tool publicly!)_

What is the order of the blocks returned by `Chunk.stream_blocks()`? I presume the first block is xyz 0,0,0 for a given section. What is the second block? Is it 1,0,0? Or 0,0,1?

**Comment by 0xTiger** [comment]
The second block will be (1,0,0) 

The [docstring for Chunk.stream_blocks](https://github.com/matcool/anvil-parser/blob/c84f700076180ff9e18dc0fd0b7882ec50c943f6/anvil/chunk.py#L231..L256) mentions how blocks are indexed:

>To get an index from (x, y, z), simply do:  ``y * 256 + z * 16 + x``

and since `stream_blocks` gets indices in ascending order, that means that first x goes up, then z goes up, then y goes up

**Comment by jchubber** [comment]
Thank you! I'll close this issue.
